telerik/kendo-theme-bootstrap

demo/diagram.html, src/diagram/_layout.scss, src/diagram/_theme.scss, src/diagram/diagram.scss
Related to https://github.com/telerik/kendo/issues/6210
=> feat: Add styles for Diagram

scss/slider/_theme.scss
button size will be fixed by https://github.com/telerik/kendo-theme-default/pull/229
=> fix: slider buttons

scss/treeview/_theme.scss
=> fix: treeview focused and selected-focused state

scss/_variables.scss, scss/button/_theme.scss, scss/panelbar/_theme.scss, scss/popup/_theme.scss, scss/tabstrip/_theme.scss
Related to https://github.com/telerik/kendo-theme-bootstrap/issues/54
=> Navigation fixes

scss/slider.scss, scss/slider/_theme.scss, scss/slider/images/_slider-h.scss, scss/slider/images/_slider-v.scss
Fixes https://github.com/telerik/kendo-theme-bootstrap/issues/84
=> fix(slider): add tick images

scss/_variables.scss, scss/menu/_theme.scss
Fixes https://github.com/telerik/kendo-theme-bootstrap/issues/87
=> fix(contextmenu): update contextmenu appearance

docs/customization.md, docs/index.md
Required to ship the bootstrap theme in the Kendo UI for Angular site.
=> chore: add docs directory until v2 branch is merged

scss/dropdownlist/_theme.scss, scss/pager/_theme.scss
Fixing some visual glitches in Angular components
=> fix: pager and dropdownlist appearance

scss/action-buttons.scss, scss/action-buttons/_layout.scss, scss/action-buttons/_theme.scss, scss/dialog/_layout.scss, scss/dialog/_theme.scss
Extract action buttons to separate files
=> chore(action-buttons): add separate files for action buttons

docs/customization.md, scss/button/_theme.scss, scss/splitter/_theme.scss
properly behavior depends on changes in Default theme: https://github.com/telerik/kendo-theme-default/pull/319
=> Add styles for outline bare flat buttons

scss/splitter/_theme.scss
fixes https://github.com/telerik/kendo-theme-bootstrap/issues/148
=> Splitter fixes

scss/scrollview/_theme.scss
Closes https://github.com/telerik/kendo-theme-bootstrap/issues/108
=> fix(scrollview): add styles for scrollview pager

scss/pivotgrid/_theme.scss
Fixes https://github.com/telerik/kendo-theme-bootstrap/issues/110
=> fix(pivotgrid): apply header-bg to pivotgrid configurator

scss/pager/_theme.scss
Fixes https://github.com/telerik/kendo-theme-bootstrap/issues/109
=> fix(pager): use consistent header appearance

scss/datetime/_theme.scss, scss/slider/_theme.scss
closes https://github.com/telerik/kendo-theme-bootstrap/issues/124
closes https://github.com/telerik/kendo-theme-bootstrap/issues/125
closes https://github.com/telerik/kendo-theme-bootstrap/issues/126
=> Editors fixes

scss/mediaplayer/_theme.scss
closes https://github.com/telerik/kendo-theme-bootstrap/issues/129
=> fix(mediaplayer): add opacity to toolbar

scss/numerictextbox/_theme.scss
Dealing with https://github.com/telerik/kendo/issues/6796
=> feat(NumericTextbox): Add invalid state styling

scss/calendar/_theme.scss
closes https://github.com/telerik/kendo-theme-bootstrap/issues/136
=> chore(calendar): remove radius from dates

scss/notification/_theme.scss
closes https://github.com/telerik/kendo-theme-bootstrap/issues/147
=> Notification fixes

scss/maskedtextbox/_theme.scss
Dealing with https://github.com/telerik/kendo/issues/6825
=> fix(MaskedTextbox): Add missing invalid state border

scss/input/_theme.scss
Dealing with https://github.com/telerik/kendo/issues/6874
=> feat(DateInput): Add invalid state styles

scss/maskedtextbox/_theme.scss
https://github.com/telerik/kendo/issues/6825
=> fix(MaskedTextbox): Fix invalid state border

scss/dropdownlist/_theme.scss, scss/panelbar/_theme.scss, scss/popup/_theme.scss
closes https://github.com/telerik/kendo-theme-bootstrap/issues/176
=> Improve focus

scss/maskedtextbox/_theme.scss
https://github.com/telerik/kendo/issues/6825
=> chore(MaskedTextbox): Adjust invalid state styling for new rendering

scss/grid/_theme.scss
https://github.com/telerik/kendo/issues/6906
=> feat(Grid): Add styles for Grid column sorting order

scss/all.scss, scss/listbox.scss, scss/listbox/_layout.scss, scss/listbox/_theme.scss
https://github.com/telerik/kendo/issues/6804
=> feat: Add ListBox styles

scss/_variables.scss
=> fix: specify transition properties

scss/grid/_theme.scss
Related to https://github.com/telerik/kendo-theme-bootstrap/issues/188
=> fix(grid): border color

scss/multiselect/_theme.scss
Closes: https://github.com/telerik/kendo-theme-bootstrap/issues/202
=> fix(multiselect): border color

scss/datetime/_theme.scss
https://github.com/telerik/kendo-theme-bootstrap/issues/187
=> fix(dateinput): border, hover and focus state

scss/combobox/_theme.scss
Fox for https://github.com/telerik/kendo-theme-default/issues/425
=> fix(combobox): rtl appearance

scss/progressbar/_theme.scss
Fixes https://github.com/telerik/kendo-theme-bootstrap/issues/231
=> fix(progressbar): add styles for indetermined progressbar

scss/scheduler/_theme.scss
related https://github.com/telerik/kendo-theme-bootstrap/issues/203
=> fix(scheduler): add bacground to event with no resources

scss/map/_theme.scss
Dealing with https://github.com/telerik/kendo-theme-bootstrap/issues/228
=> fix(map): Add marker color

scss/grid/_theme.scss
Dealing with https://github.com/telerik/kendo/issues/6906
=> feat(grid): Add styles for column sorting

scss/datetime/_theme.scss
Dealing with https://github.com/telerik/kendo/issues/7129
=> feat(timepicker): Add invalid state styles

scss/datetime/_theme.scss
Dealing with https://github.com/telerik/kendo/issues/7128
=> feat(datetimepicker): Add invalid state styles

scss/_variables.scss
Related to https://github.com/telerik/kendo-theme-default/pull/501
=> chore: add invalid-border-color variable

scss/grid/_theme.scss
https://github.com/telerik/kendo/issues/6906
=> fix(grid): Tweak multiple column sorting index position

scss/grid/_theme.scss
https://github.com/telerik/kendo/issues/6906
=> fix(grid): Set fixed font-size of col sorting index to achieve alignment

scss/grid/_theme.scss
https://github.com/telerik/kendo/issues/7138
https://github.com/telerik/kendo/issues/7097
=> fix(grid): Remove selection column checkbox margin in RTL

scss/input/_theme.scss
Related to: https://github.com/telerik/kendo-theme-bootstrap/issues/257
=> Forms styling

scss/pager/_theme.scss
Closes: https://github.com/telerik/kendo-theme-bootstrap/issues/201
=> feat(pager): buttons metrics should be in ems

scss/grid/_theme.scss
https://github.com/telerik/kendo-theme-default/issues/534
=> fix(grid): Add RTL styles for dirty cells

LICENSE.md, README.md
Clarifies license terms & conditions.
=> fix: update license

scss/spreadsheet/_theme.scss
Styles for cell editor, selection and auto fill
=> fix(spreadsheet): missing indicators for spreadsheet

scss/_variables.scss, scss/notification/_theme.scss, scss/validator/_theme.scss
Related https://github.com/telerik/kendo-theme-bootstrap/issues/193
Related https://github.com/telerik/kendo-ui-core/issues/3323
=> fix(notification): use scoped variables for notification

scss/grid/_layout.scss
Dealing with first comment in telerik/kendo-theme-bootstrap#279, second point.
=> fix(grid): Fix edit textbox width variable

scss/grid/_theme.scss
related https://github.com/telerik/kendo-theme-bootstrap/issues/224
=> feat(grid): style grid filter button states

scss/spreadsheet/_theme.scss
fixes https://github.com/telerik/kendo-theme-bootstrap/issues/229
=> fix(spreadsheet): add styles for filter menu and filter button

scss/editor/_theme.scss
related https://github.com/telerik/kendo-theme-default/issues/659
=> fix(editor): add header border color for Firefox

scss/_variables.scss
Dealing with buttons in https://github.com/telerik/kendo-theme-bootstrap/issues/298
=> feat(button): Add variable for adjusted button opacity

scss/action-buttons/_theme.scss, scss/dialog/_theme.scss
Related to https://github.com/telerik/kendo-theme-bootstrap/issues/145
Requires https://github.com/telerik/kendo-theme-default/pull/689
=> fix: unify design of dialog buttons and action buttons

scss/slider/_theme.scss, scss/switch/_theme.scss
Related to: https://github.com/telerik/kendo-theme-bootstrap/issues/298
=> fix(inputs): update slider and switch appearance

scss/combobox/_theme.scss, scss/popup/_theme.scss
Dealing with https://github.com/telerik/kendo-theme-bootstrap/issues/313
=> Combobox bootstrapv4 issues

scss/_variables.scss, scss/button/_theme.scss, scss/colorpicker/_theme.scss, scss/combobox/_theme.scss, scss/datetime/_theme.scss, scss/editor/_theme.scss, scss/gantt/_theme.scss, scss/numerictextbox/_theme.scss, scss/scheduler/_theme.scss
* Targets https://github.com/telerik/kendo-theme-bootstrap/issues/313, remove foucs outline of `k-select` in combobox
* Targets https://github.com/telerik/kendo-theme-bootstrap/issues/314
* Targets https://github.com/telerik/kendo-theme-bootstrap/issues/315
* Targets https://github.com/telerik/kendo-theme-bootstrap/issues/316
**IMPORTANT** Needs before merging:
* telerik/kendo-theme-default#718
* telerik/kendo-theme-default#719
=> Fixes related to bootstrap update

scss/_variables.scss
Dealing with https://github.com/telerik/kendo-theme-bootstrap/issues/322
=> chore(grid): Adjust Grid alt and hover row opacity

docs/customization.md, package.json, scss/_bootstrap-overrides.scss, scss/_variables.scss, scss/button/_theme.scss, scss/colorpicker/_theme.scss, scss/combobox/_theme.scss, scss/datetime/_theme.scss, scss/dialog/_theme.scss, scss/editor/_theme.scss, scss/gantt/_theme.scss, scss/grid/_theme.scss, scss/input/_theme.scss, scss/menu/_theme.scss, scss/numerictextbox/_theme.scss, scss/pager/_theme.scss, scss/panelbar/_theme.scss, scss/popup/_theme.scss, scss/progressbar/_theme.scss, scss/scheduler/_theme.scss, scss/slider/_theme.scss, scss/switch/_theme.scss, scss/tooltip/_theme.scss, scss/treeview/_theme.scss
Work in progress, addressing #298.
=> Update bootstrap dependency

docs/customization.md, package.json, scss/_bootstrap-overrides.scss, scss/_variables.scss, scss/calendar/_theme.scss, scss/grid/_theme.scss, scss/input/_theme.scss, scss/listbox/_theme.scss, scss/pager/_theme.scss, scss/panelbar/_theme.scss, scss/pivotgrid/_theme.scss, scss/slider/_theme.scss, scss/switch/_theme.scss, scss/tabstrip/_theme.scss, scss/window/_theme.scss
Update themes after upgrading to Bootstra v4 beta-1
=> Themebuilder improvements

scss/spreadsheet/_theme.scss
related https://github.com/telerik/kendo-ui-core/issues/3254
=> fix(spreadsheet): make drag handle to be visible in all cases

docs/customization.md, package.json, scss/_bootstrap-overrides.scss, scss/_variables.scss, scss/notification/_theme.scss, scss/scheduler/_theme.scss, scss/window/_theme.scss
Needs https://github.com/telerik/kendo-theme-default/pull/765
Fixes https://github.com/telerik/kendo-theme-bootstrap/issues/341
Notable changes / Issues found thus far:
* Variables
* new global border color
* `$input-btn-padding-y` has new value
* button transitions are changed
* input borde rcolor is changed
* Alert / Notification
* Button group
* ~vertical button group is `display: flex` instead of `inline-flex`~ (not applicable)
* Buttons
* hover state is back
* Modal / Window / Dialog
* Progress / Progressbar
* progress bar height variable. there is also changed layout
* Other
* gradients are back
=> fix(common): update dependency to Bootstrap v4 beta-2

scss/action-buttons/_theme.scss, scss/datetime/_theme.scss
see telerik/kendo-theme-bootstrap#332
=> fix(timepicker): improve popup appearance

scss/_variables.scss, scss/calendar/_theme.scss, scss/datetime/_theme.scss
see telerik/kendo-theme-bootstrap#350
=> fix(dateinputs): apply consistent header styles

scss/spreadsheet/_theme.scss
related https://github.com/telerik/kendo-ui-core/issues/3254
=> fix(spreadsheet): improve spreadsheet active cell border by frozen cells

scss/multiselect/_theme.scss
related https://github.com/telerik/kendo-ui-core/issues/3723
=> fix(multiselect): improve height of token with empty string

.travis.yml
Related to telerik/kendo-theme-default#849
=> chore(travis): workaround travis failures

scss/button/_theme.scss
related https://github.com/telerik/kendo/issues/7846
=> feat(badge): add styles for badge

scss/_variables.scss
Related to https://github.com/telerik/kendo-theme-default/pull/858
=> chore(pager): introduce Pager padding variables
